### ISSUE TITLE
Future mod: Advanced Chimneys

### ISSUE THREAD

**Issue by MarkStrendin** [MarkStrendin/MarkPack7#6]
https://minecraft.curseforge.com/projects/advanced-chimneys

**Comment by MarkStrendin** [comment]
Crashes the game (when it's the only mod being loaded)
`[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/endertech/minecraft/mods/adchimneys/world/WorldData$BlockRandomTick
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.endertech.minecraft.mods.adchimneys.LoadingPlugin.getASMTransformerClass(LoadingPlugin.java:17)
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:20:11] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: com/endertech/minecraft/forge/coremod/hooks/BlockRandomTickHook
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: com.endertech.minecraft.forge.coremod.hooks.BlockRandomTickHook
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:20:11] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more`

**Comment by MarkStrendin** [comment]
Rejected due to a crash, turns out it was just a missing dependency that was not gracefully handled by the mod. Retesting.

**Comment by MarkStrendin** [comment]
Will need some configuration changes so it doesn't add so many items:
 - Disable "Other" and "Glass" in adchimneys/adchumneys.cfg

Looks good enough.
